api/urls.py
from django.urls import path

from . import (pasien, pengguna, 
jadwal, memeriksa, 
ruanganRS, faskes, 
rumahSakit, reservasiRS, 
transaksiRS, hotel,
ruanganHotel, reservasiHotel,
transaksiHotel, transaksiMakan,
paketMakan)

app_name = 'api'

urlpatterns = [

     # Pengguna
     path('penggunaAPI/', pengguna.penggunaAPI, name='penggunaAPI'),
     path('kodeFaskes/', pengguna.kodeFaskes, name='kodeFaskes'),
     path('registerAPI/', pengguna.registerAPI, name='registerAPI'),

     # Pasien
     path('pasienAPI/', pasien.pasienAPI, name='pasienAPI'),
     path('deletePasienAPI/', pasien.deletePasienAPI, name='deletePasienAPI'),
     path('editPasienAPI/', pasien.editPasienAPI, name='editPasienAPI'),

     # Jadwal Dokter
     path('jadwalDokterAPI/', jadwal.jadwalDokterAPI, name='jadwalDokterAPI'),

     # Appointment
     path('appointmentAPI/', memeriksa.appointmentAPI, name='appointmentAPI'),
     path('appointmentAPI2/', memeriksa.appointmentAPI2, name='appointmentAPI2'),

     # Ruangan RS
     path('ruanganRSAPI/', ruanganRS.ruanganRSAPI, name='ruanganRSAPI'),
     path('ruanganRSAPI2/', ruanganRS.ruanganRSAPI2, name='ruanganRSAPI2'),

     # Bed RS
     path('bedAPI/', ruanganRS.bedAPI, name='bedAPI'),
     path('kodeBedAPI/', ruanganRS.kodeBedAPI, name='kodeBedAPI'),
     path('deleteBedAPI/', ruanganRS.deleteBedAPI, name='deleteBedAPI'),

     # Faskes
     path('faskesAPI/', faskes.faskesAPI, name='faskesAPI'),
     path('buatFaskesAPI/', faskes.buatFaskesAPI, name='buatFaskesAPI'),
     path('updateFaskesAPI/', faskes.updateFaskesAPI, name='updateFaskesAPI'),
     path('deleteFaskesAPI/', faskes.deleteFaskesAPI, name='deleteFaskesAPI'),

     # Rumah Sakit
     path('rumahSakitAPI/', rumahSakit.rumahSakitAPI, name='rumahSakitAPI'),

     # Reservasi RS
     path('reservasiRSAPI/', reservasiRS.reservasiRSAPI, name='reservasiRSAPI'),
     path('kodeRuanganAPI/', reservasiRS.kodeRuanganAPI, name='kodeRuanganAPI'),
     path('kodeBedAPI2/', reservasiRS.kodeBedAPI, name='kodeBedAPI'),
     path('updateReservasiRSAPI/', reservasiRS.updateReservasiRSAPI, name='updateReservasiRSAPI'),
     path('deleteReservasiAPI/', reservasiRS.deleteReservasiAPI, name='deleteReservasiAPI'),

     # Transaksi RS
     path('transaksiRSAPI/', transaksiRS.transaksiRSAPI, name='transaksiRSAPI'),

     # Hotel
     path('hotelAPI/', hotel.hotelAPI, name='hotelAPI'),
     path('updateHotelAPI/', hotel.updateHotelAPI, name='updateHotelAPI'),

     # Ruangan Hotel
     path('ruanganHotelAPI/', ruanganHotel.ruanganHotelAPI, name='ruanganHotelAPI'),
     path('updateRuanganAPI/', ruanganHotel.updateRuanganAPI, name='updateRuanganAPI'),
     path('deleteRuanganAPI/', ruanganHotel.deleteRuanganAPI, name='deleteRuanganAPI'),

     # Reservasi Hotel
     path('reservasiHotelAPI/', reservasiHotel.reservasiHotelAPI, name='reservasiHotelAPI'),
     path('updateReservasiHotelAPI/', reservasiHotel.updateReservasiHotelAPI,
          name='updateReservasiHotelAPI'),
     path('deleteReservasiHotelAPI/', reservasiHotel.deleteReservasiHotelAPI),

     # Transaksi Hotel
     path('transaksiHotelAPI/', transaksiHotel.transaksiHotelAPI, name='transaksiHotelAPI'),

     # Transaksi Makan
     path('transaksiMakanAPI/', transaksiMakan.transaksiMakanAPI, name='transaksiMakanAPI'),
     
     # Paket Makan
     path('paketMakanAPI/', paketMakan.paketMakanAPI, name='paketMakanAPI'),
     path('paketMakanAPI2/', paketMakan.paketMakanAPI2, name='paketMakanAPI2'),
]

pengguna/urls.py
from django.urls import path

from . import views

app_name = 'pengguna'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register')
]

siruco_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('api/', include('api.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('pasien/', include('pasien.urls')),
    path('jadwalDokter/', include('jadwalDokter.urls')),
    path('memeriksa/', include('memeriksa.urls')),
    path('ruanganRS/', include('ruanganRS.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('faskes/', include('faskes.urls')),
    path('rumahSakit/', include('rumahSakit.urls')),
    path('transaksiRS/', include('transaksiRS.urls')),
    path('hotel/', include('hotel.urls')),
    path('ruanganHotel/', include('ruanganHotel.urls')),
    path('reservasiHotel/', include('reservasiHotel.urls')),
    path('transaksiHotel/', include('transaksiHotel.urls')),
    path('transaksiMakan/', include('transaksiMakan.urls')),
    path('paketMakan/', include('paketMakan.urls')),
]

pengguna/models.py
from django.db import models

# Create your models here.

pengguna/views.py
from re import T
from database import MyDatabase
from django.shortcuts import redirect, render

def login(request):
    return render(request, 'pengguna/login.html')

def register(request):
    return render(request, 'pengguna/register.html')

def logout(request):
    request.session['username'] = ""
    request.session['peran'] = ""
    return redirect('homepage:homepage')

templates/pengguna/login.html
{% extends "base.html" %}
{% load static %}

{% block seo %}
<meta name="description" content="">
{% endblock seo %}

{% block css %}
<link rel="stylesheet" href="{% static 'pengguna/css/style.css' %}">
{%endblock css%}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="container">
    <h3 class="login center-align green-text text-darken-2">Login</h3>
    <div class="card-panel">
        <div class="row">
            <img class="materialboxed col s12 m6" width="650" src="{% static 'img/login.jpg' %}">
            <form class="col s12 m6" id="signup-form">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">account_circle</i>
                        <input placeholder="Masukkan username anda" name="username" id="username" type="text"
                            class="validate" data-length="50">
                        <label for="username">Username</label>
                    </div>
                    <div class="input-field col s12">
                        <i class="material-icons prefix">vpn_key</i>
                        <input placeholder="Masukkan password anda" id="password" name="password" type="password"
                            class="validate" data-length="20">
                        <label for="password">Password</label>
                    </div>
                </div>
                <div id="loader"></div>
                <blockquote id="message" style="margin-top: 10px; margin-bottom: 10px;"></blockquote>
                <p class="grey-text text-darken-2" style="margin-bottom: 30px;">Belum punya akun? Silahkan <a
                        href="{% url 'pengguna:register' %}">Registrasi</a>.</p>
                <button class="btn waves-effect waves-light" type="button" id="btn-login">Submit
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'pengguna/js/pengguna.js' %}"></script>
<script src="{% static 'formValidator.js' %}"></script>
{% endblock scripts %}

templates/pengguna/register.html
{% extends "base.html" %}
{% load static %}

{% block seo %}
<meta name="description" content="">
{% endblock seo %}

{% block css %}
<link rel="stylesheet" href="{% static 'pengguna/css/style.css' %}">
{%endblock css%}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="container">
    <h3 class="login center-align green-text text-darken-2">Register</h3>
    <div class="card-panel">
        <div class="row">
            <div class="slider col s12 m6">
                <ul class="slides">
                    <li>
                        <img class="img-slides"  src="{% static 'img/pengguna_publik.jpg' %}">
                        <div class="caption center-align">
                            <h2 class="teal-text text-teal">Pengguna Publik</h2>
                        </div>
                    </li>
                    <li>
                        <img class="img-slides"  src="{% static 'img/admin.jpg' %}">
                        <div class="caption left-align">
                            <h2 class="teal-text text-teal">Admin</h2>
                        </div>
                    </li>
                    <li>
                        <img class="img-slides"  src="{% static 'img/admin_satgas.jpg' %}">
                        <div class="caption right-align">
                            <h2 class="teal-text text-teal">Admin Satgas</h2>
                        </div>
                    </li>
                    <li>
                        <img class="img-slides" src="{% static 'img/dokter.jpg' %}">
                        <div class="caption center-align">
                            <h2 class="teal-text text-teal">Dokter</h2>
                        </div>
                    </li>
                </ul>
            </div>
            <form class="col s12 m6" id="signup-form">
                {% csrf_token %}
                <div class="input-field col s12">
                    <i class="material-icons prefix">people</i>
                    <select name="role" id="role-select">
                        <option value="" disabled selected>Pilih...</option>
                        <option value="admin">Admin</option>
                        <option value="admin_satgas">Admin Satgas</option>
                        <option value="dokter">Dokter</option>
                        <option value="pengguna_publik">Pengguna Publik</option>
                    </select>
                    <label>Peran</label>
                </div>
                <div id="role-form" class="col s12"></div>
                <div id="loader"></div>
                <button class="btn waves-effect waves-light" type="button" id="btn-register" style="margin-top: 10px;">Register
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'pengguna/js/register.js' %}"></script>
<script src="{% static 'pengguna/js/pengguna.js' %}"></script>
{% endblock scripts %}

templates/pengguna/temp.html
<div class="row">
    <div class="input-field col s12">
        <i class="material-icons prefix">account_circle</i>
        <input name="username" id="username" type="text" class="validate inputan" data-length="50">
        <label for="first_name">Username</label>
    </div>
</div>
<div class="row">
    <div class="input-field col s12">
        <i class="material-icons prefix">vpn_key</i>
        <input id="password" name="password" type="password"
            class="validate inputan" data-length="20">
        <label for="password">Password</label>
    </div>
</div>
<div class="row">
    <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <input id="icon_prefix" name="nama" id="nama" type="text" class="validate">
        <label for="icon_prefix">Nama</label>
    </div>
    <div class="input-field col s6">
        <i class="material-icons prefix">phone</i>
        <input id="icon_telephone" id="no_telp" name="no_telp" type="tel" class="validate">
        <label for="icon_telephone">Telephone</label>
    </div>
</div>
<div class="row">
    <div class="input-field col s12">
        <i class="material-icons prefix">assignment_ind</i>
        <input id="icon_prefix" name="nik" id="nik" type="text" class="validate">
        <label for="icon_prefix">NIK</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        <i class="material-icons prefix">assignment_ind</i>
        <input id="icon_prefix" name="no_str" id="no_str" type="text" class="validate">
        <label for="icon_prefix">No.STR</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <input id="icon_prefix" name="gelar_depan" id="gelar_depan" type="text" class="validate">
        <label for="icon_prefix">Gelar Depan</label>
    </div>
    <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <input id="icon_telephone" id="gelar_belakang" name="gelar_belakang" type="tel" class="validate">
        <label for="icon_telephone">Gelar Belakang</label>
    </div>
</div>

<div class="row">
    <div class="input-field col s12">
        <i class="material-icons prefix">code</i>
        <select name="kode_faskes" id="kode_faskes">
            <option value="" disabled selected>Pilih...</option>
        </select>
        <label>Pilih Kode Faskes</label>
    </div>
</div>