api/urls.py
from django.urls import path

from . import (pasien, pengguna, 
jadwal, memeriksa, 
ruanganRS, faskes, 
rumahSakit, reservasiRS, 
transaksiRS, hotel,
ruanganHotel, reservasiHotel,
transaksiHotel, transaksiMakan,
paketMakan)

app_name = 'api'

urlpatterns = [

     # Pengguna
     path('penggunaAPI/', pengguna.penggunaAPI, name='penggunaAPI'),
     path('kodeFaskes/', pengguna.kodeFaskes, name='kodeFaskes'),
     path('registerAPI/', pengguna.registerAPI, name='registerAPI'),

     # Pasien
     path('pasienAPI/', pasien.pasienAPI, name='pasienAPI'),
     path('deletePasienAPI/', pasien.deletePasienAPI, name='deletePasienAPI'),
     path('editPasienAPI/', pasien.editPasienAPI, name='editPasienAPI'),

     # Jadwal Dokter
     path('jadwalDokterAPI/', jadwal.jadwalDokterAPI, name='jadwalDokterAPI'),

     # Appointment
     path('appointmentAPI/', memeriksa.appointmentAPI, name='appointmentAPI'),
     path('appointmentAPI2/', memeriksa.appointmentAPI2, name='appointmentAPI2'),

     # Ruangan RS
     path('ruanganRSAPI/', ruanganRS.ruanganRSAPI, name='ruanganRSAPI'),
     path('ruanganRSAPI2/', ruanganRS.ruanganRSAPI2, name='ruanganRSAPI2'),

     # Bed RS
     path('bedAPI/', ruanganRS.bedAPI, name='bedAPI'),
     path('kodeBedAPI/', ruanganRS.kodeBedAPI, name='kodeBedAPI'),
     path('deleteBedAPI/', ruanganRS.deleteBedAPI, name='deleteBedAPI'),

     # Faskes
     path('faskesAPI/', faskes.faskesAPI, name='faskesAPI'),
     path('buatFaskesAPI/', faskes.buatFaskesAPI, name='buatFaskesAPI'),
     path('updateFaskesAPI/', faskes.updateFaskesAPI, name='updateFaskesAPI'),
     path('deleteFaskesAPI/', faskes.deleteFaskesAPI, name='deleteFaskesAPI'),

     # Rumah Sakit
     path('rumahSakitAPI/', rumahSakit.rumahSakitAPI, name='rumahSakitAPI'),

     # Reservasi RS
     path('reservasiRSAPI/', reservasiRS.reservasiRSAPI, name='reservasiRSAPI'),
     path('kodeRuanganAPI/', reservasiRS.kodeRuanganAPI, name='kodeRuanganAPI'),
     path('kodeBedAPI2/', reservasiRS.kodeBedAPI, name='kodeBedAPI'),
     path('updateReservasiRSAPI/', reservasiRS.updateReservasiRSAPI, name='updateReservasiRSAPI'),
     path('deleteReservasiAPI/', reservasiRS.deleteReservasiAPI, name='deleteReservasiAPI'),

     # Transaksi RS
     path('transaksiRSAPI/', transaksiRS.transaksiRSAPI, name='transaksiRSAPI'),

     # Hotel
     path('hotelAPI/', hotel.hotelAPI, name='hotelAPI'),
     path('updateHotelAPI/', hotel.updateHotelAPI, name='updateHotelAPI'),

     # Ruangan Hotel
     path('ruanganHotelAPI/', ruanganHotel.ruanganHotelAPI, name='ruanganHotelAPI'),
     path('updateRuanganAPI/', ruanganHotel.updateRuanganAPI, name='updateRuanganAPI'),
     path('deleteRuanganAPI/', ruanganHotel.deleteRuanganAPI, name='deleteRuanganAPI'),

     # Reservasi Hotel
     path('reservasiHotelAPI/', reservasiHotel.reservasiHotelAPI, name='reservasiHotelAPI'),
     path('updateReservasiHotelAPI/', reservasiHotel.updateReservasiHotelAPI,
          name='updateReservasiHotelAPI'),
     path('deleteReservasiHotelAPI/', reservasiHotel.deleteReservasiHotelAPI),

     # Transaksi Hotel
     path('transaksiHotelAPI/', transaksiHotel.transaksiHotelAPI, name='transaksiHotelAPI'),

     # Transaksi Makan
     path('transaksiMakanAPI/', transaksiMakan.transaksiMakanAPI, name='transaksiMakanAPI'),
     
     # Paket Makan
     path('paketMakanAPI/', paketMakan.paketMakanAPI, name='paketMakanAPI'),
     path('paketMakanAPI2/', paketMakan.paketMakanAPI2, name='paketMakanAPI2'),
]

pasien/urls.py
from django.urls import path

from . import views

app_name = 'pasien'

urlpatterns = [
    path('daftar_pasien/', views.daftar_pasien, name='daftar_pasien'),
    path('list_pasien/', views.list_pasien, name='list_pasien'),
    path('edit_pasien/<str:pk>/', views.edit_pasien, name='edit_pasien'),
]

siruco_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('api/', include('api.urls')),
    path('pengguna/', include('pengguna.urls')),
    path('pasien/', include('pasien.urls')),
    path('jadwalDokter/', include('jadwalDokter.urls')),
    path('memeriksa/', include('memeriksa.urls')),
    path('ruanganRS/', include('ruanganRS.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('faskes/', include('faskes.urls')),
    path('rumahSakit/', include('rumahSakit.urls')),
    path('transaksiRS/', include('transaksiRS.urls')),
    path('hotel/', include('hotel.urls')),
    path('ruanganHotel/', include('ruanganHotel.urls')),
    path('reservasiHotel/', include('reservasiHotel.urls')),
    path('transaksiHotel/', include('transaksiHotel.urls')),
    path('transaksiMakan/', include('transaksiMakan.urls')),
    path('paketMakan/', include('paketMakan.urls')),
]

pasien/models.py
from django.db import models

# Create your models here.

pasien/views.py
from django.shortcuts import render
from database import MyDatabase

def daftar_pasien(request):
    return render(request, 'pasien/daftar_pasien.html')

def list_pasien(request):
    db = MyDatabase()
    username = request.session['username']
    query = f"SELECT nik, nama FROM PASIEN WHERE idpendaftar='{username}'"
    result = db.query(query=query, fetchAll=True)
    db.close()
    return render(request, 'pasien/list_pasien.html', {"dataPasien": result})

def edit_pasien(request, pk):
    db = MyDatabase()
    query = f"SELECT nik, nama FROM PASIEN WHERE nik='{pk}'"
    result = db.query(query=query, fetchOne=True)
    db.close()
    context = {"nik": result[0], "nama": result[1]}
    return render(request, 'pasien/edit_pasien.html', context)

templates/pasien/daftar_pasien.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{% endblock css%}

{% block title %}Daftar Pasien{% endblock title %}

{% block content %}
<div class="container">
    <h3 class="login center-align green-text text-darken-2">Daftar Pasien</h3>
    <div class="card-panel">
        <h6 class="black-text text-black">Masukkan data diri pasien.</h6>
        <form class="col s12" id="pasien-form">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input value="{{request.session.username}}" name="pendaftar" id="pendaftar" type="text" class="validate"disabled>
                    <label for="icon_prefix">Pendaftar</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="nik" id="nik" type="text" class="validate">
                    <label for="icon_prefix">NIK</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="nama" id="nama" type="text" class="validate">
                    <label for="icon_prefix">Nama</label>
                </div>
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">phone</i>
                    <input id="no_telp" name="no_telp" type="tel" class="validate">
                    <label for="icon_telephone">No Telepon</label>
                </div>
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">contact_phone</i>
                    <input id="no_hp" name="no_hp" type="tel" class="validate">
                    <label for="icon_telephone">No HP</label>
                </div>
            </div>

            <h6 class="black-text text-black">Alamat (Sesuai KTP)</h6>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="jalan_ktp" id="jalan_ktp" type="text" class="validate">
                    <label for="icon_prefix">Jalan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kel_ktp" id="kel_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kelurahan</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="kec_ktp" id="kec_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kecamatan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kab_ktp" id="kab_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kabupaten/Kota</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="prov_ktp" id="prov_ktp" type="text" class="validate">
                    <label for="icon_prefix">Provinsi</label>
                </div>
            </div>

            <h6 class="black-text text-black">Alamat (Domisili)</h6>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="jalan_dom" id="jalan_dom" type="text" class="validate">
                    <label for="icon_prefix">Jalan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kel_dom" id="kel_dom" type="text" class="validate">
                    <label for="icon_prefix">Kelurahan</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="kec_dom" id="kec_dom" type="text" class="validate">
                    <label for="icon_prefix">Kecamatan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kab_dom" id="kab_dom" type="text" class="validate">
                    <label for="icon_prefix">Kabupaten/Kota</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="prov_dom" id="prov_dom" type="text" class="validate">
                    <label for="icon_prefix">Provinsi</label>
                </div>
            </div>
            <div id="loader"></div>
            <blockquote id="message" style="margin-top: 10px; margin-bottom: 10px;"></blockquote>
            <button class="btn waves-effect waves-light" type="button" id="btn-daftar">Daftar Pasien
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'pasien/js/pasien.js' %}"></script>
<script src="{% static 'formValidator.js' %}"></script>
{% endblock scripts %}

templates/pasien/edit_pasien.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{% endblock css%}

{% block title %}Edit Pasien{% endblock title %}

{% block content %}
{% csrf_token %}
<div class="container">
    <h3 class="login center-align green-text text-darken-2">Edit Pasien</h3>
    <div class="card-panel">
        <h6 class="black-text text-black">Masukkan data diri pasien.</h6>
        <form class="col s12" id="pasien-form">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input value="{{request.session.username}}" name="pendaftar" id="pendaftar" type="text"
                        class="validate" disabled>
                    <label for="icon_prefix">Pendaftar</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input value="{{nik}}" name="nik" id="nik" type="text" class="validate" readonly>
                    <label for="icon_prefix">NIK</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">account_circle</i>
                    <input value="{{nama}}" name="nama" id="nama" type="text" class="validate" disabled>
                    <label for="icon_prefix">Nama</label>
                </div>
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">phone</i>
                    <input id="no_telp" name="no_telp" type="tel" class="validate">
                    <label for="icon_telephone">No Telepon</label>
                </div>
                <div class="input-field col s12 m4">
                    <i class="material-icons prefix">contact_phone</i>
                    <input id="no_hp" name="no_hp" type="tel" class="validate">
                    <label for="icon_telephone">No HP</label>
                </div>
            </div>

            <h6 class="black-text text-black">Alamat (Sesuai KTP)</h6>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="jalan_ktp" id="jalan_ktp" type="text" class="validate">
                    <label for="icon_prefix">Jalan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kel_ktp" id="kel_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kelurahan</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="kec_ktp" id="kec_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kecamatan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kab_ktp" id="kab_ktp" type="text" class="validate">
                    <label for="icon_prefix">Kabupaten/Kota</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="prov_ktp" id="prov_ktp" type="text" class="validate">
                    <label for="icon_prefix">Provinsi</label>
                </div>
            </div>

            <h6 class="black-text text-black">Alamat (Domisili)</h6>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="jalan_dom" id="jalan_dom" type="text" class="validate">
                    <label for="icon_prefix">Jalan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kel_dom" id="kel_dom" type="text" class="validate">
                    <label for="icon_prefix">Kelurahan</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="kec_dom" id="kec_dom" type="text" class="validate">
                    <label for="icon_prefix">Kecamatan</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">account_circle</i>
                    <input name="kab_dom" id="kab_dom" type="text" class="validate">
                    <label for="icon_prefix">Kabupaten/Kota</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <input name="prov_dom" id="prov_dom" type="text" class="validate">
                    <label for="icon_prefix">Provinsi</label>
                </div>
            </div>
            <div class="loader"></div>
            <button class="btn waves-effect waves-light" type="button" id="btn-edit">Edit Pasien
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'pasien/js/pasien.js' %}"></script>
{% endblock scripts %}

templates/pasien/list_pasien.html
{% extends "base.html" %}
{% load static %}

{% block css %}

{% endblock css%}

{% block title %}List Pasien{% endblock title %}

{% block content %}
{% csrf_token %}
<div id="modal1" class="modal">
    <div class="modal-content">
        <h4 id="detail-header"></h4>
        <div class="" id="loader-modal">
            <div class="indeterminate"></div>
        </div>
        <div>
            <div class="card-panel" id="detail-text"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="modal-close btn-small waves-effect waves-light" type="button">TUTUP</button>
    </div> 
</div>

<div class="container">
    <h3 class="login center-align green-text text-darken-2">List Pasien</h3>
    <div class="card-panel">
        <div id="loader"></div>
        <table class="highlight responsive-table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>NIK</th>
                    <th>Nama Pasien</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="table-body">
                {% for pasien in dataPasien %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ pasien.0 }}</td>
                        <td>{{ pasien.1 }}</td>
                        <td>
                            <a class="waves-effect waves-light btn-small lime edit-btn" href="{% url 'pasien:edit_pasien' pasien.0 %}">
                                <i class="material-icons">edit</i>
                            </a>
                            <a class="btn-small waves-effect waves-light red delete-btn"><i
                                    class="material-icons">delete</i></a>
                            <a class="waves-effect waves-light btn-small detail-btn modal-trigger"
                                href="#modal1">Detail</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'pasien/js/pasien.js' %}"></script>
{% endblock scripts %}